### ISSUE TITLE
Landing Page Content too wide

### ISSUE THREAD

**Issue by acatzk** [VeoScript/veo#21]
**Please set the max width size to make it look closer**
![landingpage](https://user-images.githubusercontent.com/38458781/113716046-bff03100-971c-11eb-9748-e922b657f435.png)

**Comment by VeoScript** [comment]
I never thought it would be that big on a large screen. I am using justify-around.
![image](https://user-images.githubusercontent.com/26340308/113718446-39891e80-971f-11eb-8630-7900b1bf2d5c.png)
